### ISSUE TITLE
respond to "pomoc"

### ISSUE THREAD

**Issue by Treyone** [zavenco/hubot-wordpress#1]
Hello,

it seems that the direct message response is triggered by "pomoc" instead of HUBOT_WORDPRESS_RESPOND_TRIGGER. It that a mistake or a wanted behavior ?
If this is a mistake, I can off course PR an correction.

**Comment by kr00p** [comment]
Thank you for noticing. Please feel free to PR the fix.

**Comment by Treyone** [comment]
I didn't update the package.json, as I thought you CI would do it, but apparently it's not the case. Do you want me to PR again ?
What about NPM update ?

**Comment by kr00p** [comment]
No problem, already taken care of :)
